### ISSUE TITLE
GCov not detected on OS X travis image

### ISSUE THREAD

**Issue by horenmar** [RWTH-HPC/CMake-codecov#12]
I am trying to use `CMake-codecov` to capture code coverage for [Catch](https://github.com/catchorg/Catch2/) and after some bumbling around I got it to work properly under Linux for both GCC and Clang.

However, I ran into trouble when I was trying to integrate it with OS X builds. The scripts properly detect that AppleClang supports coverage, finds `lcov`, but then is unable to find `gcov`, with this output

```
CMake Warning at CMake/FindGcov.cmake:129 (message):
  No coverage evaluation binary found for AppleClang.

Call Stack (most recent call first):
  CMake/Findcodecov.cmake:248 (add_gcov_target)
  CMake/Findcodecov.cmake:38 (add_coverage_target)
  CMakeLists.txt:308 (add_coverage)


CMake Warning at CMake/FindLcov.cmake:154 (message):
  No coverage evaluation binary found for AppleClang.

Call Stack (most recent call first):
  CMake/FindLcov.cmake:39 (lcov_capture_initial_tgt)
  CMake/Findcodecov.cmake:249 (add_lcov_target)
  CMake/Findcodecov.cmake:38 (add_coverage_target)
  CMakeLists.txt:308 (add_coverage)


CMake Warning at CMake/FindLcov.cmake:245 (message):
  No coverage evaluation binary found for AppleClang.

Call Stack (most recent call first):
  CMake/FindLcov.cmake:42 (lcov_capture_tgt)
  CMake/Findcodecov.cmake:249 (add_lcov_target)
  CMake/Findcodecov.cmake:38 (add_coverage_target)
  CMakeLists.txt:308 (add_coverage)
```

The full travis output can be found [here](https://travis-ci.org/catchorg/Catch2/jobs/307866219).

Btw, thanks for the script. After I stopped being dumb about using it on Linux, it worked nicely.

**Comment by alehaa** [comment]
Sorry, but where can I find informations about the error message? The linked Travis CI job has no such message ...

**Comment by horenmar** [comment]
You have to click the "raw log" button, as Travis helpfully tries to filter out unimportant messages...

**Comment by alehaa** [comment]
I see, thanks. For the record: it's in [line 644](https://travis-ci.org/catchorg/Catch2/jobs/307866219#L644).

I'll try to check whats going on there. Had some trouble with coverage at macOS, too.

**Comment by rene-aguirre** [comment]
This works for me on OS X:

```
diff --git a/cmake/FindGcov.cmake b/cmake/FindGcov.cmake
index 4141711..e346e0a 100644
--- a/cmake/FindGcov.cmake
+++ b/cmake/FindGcov.cmake
@@ -35,7 +35,7 @@ foreach (LANG ${ENABLED_LANGUAGES})
                        find_program(GCOV_BIN NAMES gcov-${GCC_VERSION} gcov
                                HINTS ${COMPILER_PATH})

-               elseif ("${CMAKE_${LANG}_COMPILER_ID}" STREQUAL "Clang")
+               elseif ("${CMAKE_${LANG}_COMPILER_ID}" MATCHES "^(Apple)?Clang$")
                        # Some distributions like Debian ship llvm-cov with the compiler
                        # version appended as llvm-cov-x.y. To find this binary we'll build
                        # the suggested binary name with the compiler version.
```

**Comment by alehaa** [comment]
This should be solved by merging the PR now. However, lcov seems not to be compatible with some gcc versions anymore.
