### ISSUE TITLE
Travis won't build without errors

### ISSUE THREAD

**Issue by farrrb** [RWTH-HPC/CMake-codecov#13]
Hi, i just forked this project in order to add some support for windows platforms. When i added the project into travis i saw that the build fails for the "clang-builds" (on branch master). 

Would you please take a look into this and maybe rerun your builds as well?

https://travis-ci.org/farrrb/CMake-codecov/builds/335606460

Thank you,
Fabian

**Comment by alehaa** [comment]
Except for the macOS testcases, these should work now. The macOS problems will be addressed by #12.
