### ISSUE TITLE
ENABLE_COVERAGE_ALL

### ISSUE THREAD

**Issue by ludkinm** [RWTH-HPC/CMake-codecov#25]
HI,
Where is the `ENABLE_COVERAGE_ALL` option applied?
I can't see a reference to it in the source.

**Comment by alehaa** [comment]
Seems I removed it in 79b8a8092b9df857bf2b2705ad9af9bf2dc62825 without modifying the documentation.

**Comment by alehaa** [comment]
Fixed `README.md` in c3361ca14249c28e467b70c8d157c4c4eb25e51b.
